spring.application.name=digital-banking-transfer-ledger

spring.datasource.url=jdbc:postgresql://localhost:5432/digital_banking
spring.datasource.username=qnb_user
spring.datasource.password=qnb_password

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true